/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.bric3.drain;

import java.nio.file.Path;
import java.nio.file.Paths;

public class TailFollow {

    public static final int ERR_NO_FILEPATH = 1;

    public static void main(String[] args) {
        if(args.length != 1) {
            System.err.println("Expects the file path to tail!");
            System.exit(ERR_NO_FILEPATH);
        }

        final Path path = Paths.get(args[0]);

        System.out.println(path);
    }
}
