name: Master Build
on: 
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    continue-on-error: ${{ matrix.experimental }}
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        experimental: [false]
        include:
          - os: windows-latest
            experimental: true
          - os: macos-latest
            experimental: true
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - name: Setup JVM
      uses: actions/setup-java@v3
      with:
        distribution : zulu
        java-version: |
          19
          17
    - name : Setup Gradle
      uses : gradle/gradle-build-action@v2
    - run: ./gradlew build
#    - name: list build directory
#      if: ${{ always() }}
#      run: |
#        ls build

    - uses: mikepenz/action-junit-report@v3
      if: ${{ always() }}
      name: Publish Test Report
      with:
        check_name: Test Report - ${{ matrix.os }}
        report_paths: '**/build/test-results/test/TEST-*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}


#  publish-test-results:
#    name: "Publish Unit Tests Results"
#    needs: gradle
#    runs-on: ubuntu-latest
#    # the build-and-test job might be skipped, we don't need to run this job then
#    if: success() || failure()
#
#    steps:
#      - name: Download Artifacts
#        uses: actions/download-artifact@v2
#        with:
#          path: artifacts
#
#      - name: Publish Unit Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v1.6
#        with:
#          check_name: Unit Test Results
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          files: pytest.xml


  publish:
    name: Publish snapshots
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - uses: gradle/wrapper-validation-action@v1
    - name: Setup JVM
      uses: actions/setup-java@v3
      with:
        distribution : zulu
        java-version: |
          19
          17
    - name : Setup Gradle
      uses : gradle/gradle-build-action@v2
    - run: ./gradlew snapshot -Ppublish.central=true
      if: success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ORG_GRADLE_PROJECT_OSSRHUSERNAME }}
        ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ORG_GRADLE_PROJECT_OSSRHPASSWORD }}
